x-defaults: &defaults
  image: leftys/copytrader
  environment:
    ACCOUNT_TO_COPY: ${ACCOUNT_TO_COPY}
    TRADING_ADDRESS: ${TRADING_ADDRESS}
    ACCOUNT_ADDRESS: ${ACCOUNT_ADDRESS}
    VAULT_ADDRESS: ${VAULT_ADDRESS}
    PRIVATE_KEY_API: ${PRIVATE_KEY_API}
    LEVERAGE: ${LEVERAGE}
    SLEEP_INTERVAL: ${SLEEP_INTERVAL}
    SENTRY_DSN: ${SENTRY_DSN}
    ENVIRONMENT: ${ENVIRONMENT}
    PROFILE: ${PROFILE}
  restart: unless-stopped
  stop_grace_period: 2s
  deploy:
    resources:
      limits:
        cpus: '0.2'
        memory: 150M

services:
  order_bot:
    <<: *defaults
    environment:
      RELEASE: ${COMPOSE_PROJECT_NAME:-copytrader}-order_bot-${IMAGE_HASH:-latest}
    command: python -u order_bot.py

  position_bot:
    <<: *defaults
    environment:
      RELEASE: ${COMPOSE_PROJECT_NAME:-copytrader}-position_bot-${IMAGE_HASH:-latest}
    command: python -u position_bot.py
